import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service · Educate',
  description: 'Terms of using Educate.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-neutral-950 text-neutral-200">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <Link href="/" className="text-sm text-indigo-400 no-underline hover:underline">
          {'\u2190'} Back to home
        </Link>

        <h1 className="text-3xl sm:text-4xl font-extrabold text-white mt-6 mb-2">Terms of Service</h1>
        <p className="text-xs text-neutral-500 mb-8">Last updated: 6 April 2026</p>

        <div className="space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-white mb-2">1. Acceptance</h2>
            <p className="m-0">
              By creating an account or using Educate you agree to these Terms and to our{' '}
              <Link href="/privacy" className="text-indigo-400 no-underline">Privacy Policy</Link>.
              If you don&rsquo;t agree, please don&rsquo;t use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">2. What Educate is</h2>
            <p className="m-0">
              Educate is a study tool that helps you revise for GCSE exams. It provides quizzes,
              flashcards, AI-generated explanations and progress tracking. It is <strong>not</strong>{' '}
              a replacement for your school, your teachers or official exam-board materials.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">3. AI-generated content</h2>
            <p className="m-0">
              Some questions, flashcards and explanations are generated by an AI model
              (Anthropic&rsquo;s Claude). AI can make mistakes. Always check important answers
              against your textbook, teacher or exam-board specification before relying on them in
              an exam.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">4. Acceptable use</h2>
            <p className="m-0 mb-2">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 m-0">
              <li>Use the service for anything illegal or harmful</li>
              <li>Attempt to extract, scrape or reverse-engineer the AI model</li>
              <li>Try to bypass usage limits or security controls</li>
              <li>Submit content that is abusive, hateful, sexual or discriminatory</li>
              <li>Share your account with others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">5. Your account</h2>
            <p className="m-0">
              You&rsquo;re responsible for keeping your sign-in details safe. Tell us straight away
              if you think someone else has accessed your account. We may suspend accounts that
              break these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">6. Subscriptions &amp; payments</h2>
            <p className="m-0">
              Educate is currently free to use. If we introduce paid features in the future, you
              will be asked to opt in before any payment is taken and the pricing will be shown
              clearly first.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">7. Intellectual property</h2>
            <p className="m-0">
              The Educate name, logo, code and original content belong to us. Past-paper questions
              and exam-board names belong to their respective owners and are used for educational
              purposes. You keep ownership of any notes or content you create.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">8. Availability &amp; changes</h2>
            <p className="m-0">
              We try to keep Educate online, but we don&rsquo;t guarantee uninterrupted access.
              We may add, change or remove features at any time. If we make a major change that
              affects you, we&rsquo;ll let you know in the app.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">9. Liability</h2>
            <p className="m-0">
              To the extent permitted by law, Educate is provided &ldquo;as is&rdquo;. We&rsquo;re
              not liable for exam outcomes, lost study data, or indirect losses caused by use of
              the service. Nothing in these Terms limits liability for things the law does not
              allow us to limit (such as death or personal injury caused by negligence).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">10. Closing your account</h2>
            <p className="m-0">
              You can delete your account from your profile settings at any time. We will erase
              your personal data within 30 days, except where we&rsquo;re required by law to keep it.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">11. Governing law</h2>
            <p className="m-0">
              These Terms are governed by the laws of England and Wales. Any disputes will be
              handled by the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">12. Contact</h2>
            <p className="m-0">
              Questions about these Terms? Email{' '}
              <a className="text-indigo-400" href="mailto:hello@educate.app">hello@educate.app</a>.
            </p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-neutral-800 flex gap-4 text-xs text-neutral-500">
          <Link href="/privacy" className="text-indigo-400 no-underline hover:underline">Privacy Policy</Link>
          <Link href="/" className="text-indigo-400 no-underline hover:underline">Home</Link>
        </div>
      </div>
    </div>
  );
}
