'use client';

import { useState, useEffect, useRef } from 'react';
import { useUser } from '@clerk/nextjs';
import { Sidebar, MobileNav } from '@/components/layout/Sidebar';
import { useToast } from '@/components/ui/Toast';
import { getStreakData } from '@/lib/streak';
import { getUnlockedAchievements } from '@/lib/achievements';
import { levelFromXP, getLevelTitle } from '@/lib/xp-client';

interface ExportData {
  name: string;
  level: number;
  title: string;
  xp: number;
  streak: number;
  longestStreak: number;
  quizCount: number;
  accuracy: number;
  achievements: number;
  totalAchievements: number;
  subjects: { subject: string; board: string }[];
  timerMinutes: number;
}

function gatherExportData(userName: string): ExportData {
  const streak = getStreakData();
  const achievements = getUnlockedAchievements();

  let xp = 0;
  try {
    const raw = localStorage.getItem('educate-profile-cache');
    if (raw) { const d = JSON.parse(raw); xp = d.xp || 0; }
  } catch {}

  let quizCount = 0, totalCorrect = 0, totalQuestions = 0;
  try {
    const raw = localStorage.getItem('educate-quiz-stats');
    if (raw) {
      const d = JSON.parse(raw);
      quizCount = d.count || 0;
      totalCorrect = d.correct || 0;
      totalQuestions = d.total || 0;
    }
  } catch {}

  let timerMinutes = 0;
  try {
    const raw = localStorage.getItem('educate-timer-stats');
    if (raw) { const d = JSON.parse(raw); timerMinutes = d.totalMinutes || 0; }
  } catch {}

  let subjects: { subject: string; board: string }[] = [];
  try {
    const raw = localStorage.getItem('educate-user-subjects');
    if (raw) subjects = JSON.parse(raw);
  } catch {}

  return {
    name: userName,
    level: levelFromXP(xp),
    title: getLevelTitle(levelFromXP(xp)),
    xp,
    streak: streak.currentStreak,
    longestStreak: streak.longestStreak,
    quizCount,
    accuracy: totalQuestions > 0 ? Math.round((totalCorrect / totalQuestions) * 100) : 0,
    achievements: achievements.length,
    totalAchievements: 20,
    subjects,
    timerMinutes,
  };
}

export default function ExportPage() {
  const { user } = useUser();
  const { showToast } = useToast();
  const [data, setData] = useState<ExportData | null>(null);
  const cardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const name = user?.firstName || user?.fullName || 'Student';
    setData(gatherExportData(name));
  }, [user]);

  async function handleDownloadCard() {
    if (!cardRef.current) return;
    try {
      // Use html2canvas-style approach — render to canvas via SVG foreignObject
      const el = cardRef.current;
      const svgData = `
        <svg xmlns="http://www.w3.org/2000/svg" width="${el.offsetWidth}" height="${el.offsetHeight}">
          <foreignObject width="100%" height="100%">
            <div xmlns="http://www.w3.org/1999/xhtml">
              ${el.outerHTML}
            </div>
          </foreignObject>
        </svg>`;

      // Just copy text summary to clipboard instead (more reliable)
      await copyTextReport();
    } catch {
      showToast({ icon: '\u{274C}', title: 'Could not generate image', type: 'info' });
    }
  }

  async function copyTextReport() {
    if (!data) return;
    const text = [
      `\u{1F4DA} Educate GCSE Revision Report`,
      `\u{1F464} ${data.name}`,
      `\u{2B50} Level ${data.level} (${data.title}) \u2014 ${data.xp.toLocaleString()} XP`,
      `\u{1F525} ${data.streak}-day streak (longest: ${data.longestStreak})`,
      `\u{1F4DD} ${data.quizCount} quizzes completed (${data.accuracy}% accuracy)`,
      `\u{23F0} ${Math.round(data.timerMinutes / 60 * 10) / 10} hours of focused study`,
      `\u{1F3C6} ${data.achievements}/${data.totalAchievements} achievements unlocked`,
      ``,
      `Subjects: ${data.subjects.map(s => `${s.subject} (${s.board})`).join(', ')}`,
      ``,
      `Generated by Educate \u2014 GCSE Revision App`,
    ].join('\n');

    try {
      await navigator.clipboard.writeText(text);
      showToast({ icon: '\u{1F4CB}', title: 'Report copied to clipboard!', type: 'success' });
    } catch {
      showToast({ icon: '\u{274C}', title: 'Could not copy to clipboard', type: 'info' });
    }
  }

  function downloadTextReport() {
    if (!data) return;
    const text = [
      'EDUCATE - GCSE REVISION REPORT',
      '================================',
      '',
      `Student: ${data.name}`,
      `Level: ${data.level} (${data.title})`,
      `Total XP: ${data.xp.toLocaleString()}`,
      '',
      'STATISTICS',
      '----------',
      `Current Streak: ${data.streak} days`,
      `Longest Streak: ${data.longestStreak} days`,
      `Quizzes Completed: ${data.quizCount}`,
      `Overall Accuracy: ${data.accuracy}%`,
      `Study Time: ${Math.round(data.timerMinutes / 60 * 10) / 10} hours`,
      `Achievements: ${data.achievements}/${data.totalAchievements}`,
      '',
      'SUBJECTS',
      '--------',
      ...data.subjects.map(s => `- ${s.subject} (${s.board})`),
      '',
      '================================',
      `Generated on ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`,
      'Educate - GCSE Revision App',
    ].join('\n');

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `educate-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    showToast({ icon: '\u{1F4E5}', title: 'Report downloaded!', type: 'success' });
  }

  function downloadTimetablePrint() {
    try {
      const raw = localStorage.getItem('educate-timetable');
      if (!raw) {
        showToast({ icon: '\u{26A0}\uFE0F', title: 'No timetable to export', type: 'info' });
        return;
      }
      const tt = JSON.parse(raw);
      const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

      let html = `<!DOCTYPE html><html><head><title>Revision Timetable</title>
        <style>
          body { font-family: system-ui, sans-serif; background: #fff; color: #333; padding: 20px; }
          h1 { text-align: center; margin-bottom: 20px; }
          .week { margin-bottom: 30px; }
          .week h2 { font-size: 16px; border-bottom: 2px solid #6366f1; padding-bottom: 4px; }
          .grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 8px; }
          .day { background: #f5f5f5; border-radius: 8px; padding: 8px; min-height: 80px; }
          .day-name { font-weight: bold; font-size: 12px; margin-bottom: 6px; }
          .slot { background: #e8e5ff; border-radius: 4px; padding: 4px 6px; margin-bottom: 4px; font-size: 11px; }
          @media print { body { padding: 10px; } }
        </style>
      </head><body><h1>Revision Timetable</h1>`;

      for (let w = 0; w < tt.weeks; w++) {
        html += `<div class="week"><h2>Week ${w + 1}</h2><div class="grid">`;
        for (const day of days) {
          const key = `${w}-${day}`;
          const slots: { subject: string; time: string }[] = tt.schedule[key] || [];
          html += `<div class="day"><div class="day-name">${day}</div>`;
          slots.forEach(s => {
            if (s.subject) html += `<div class="slot">${s.subject}<br><small>${s.time}</small></div>`;
          });
          html += `</div>`;
        }
        html += `</div></div>`;
      }
      html += `</body></html>`;

      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'revision-timetable.html';
      a.click();
      URL.revokeObjectURL(url);
      showToast({ icon: '\u{1F5A8}\uFE0F', title: 'Timetable exported! Open & print the HTML file.', type: 'success' });
    } catch {
      showToast({ icon: '\u{274C}', title: 'Export failed', type: 'info' });
    }
  }

  if (!data) return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="text-neutral-500 text-sm">Loading...</div>
    </div>
  );

  return (
    <div className="flex min-h-screen">
      <Sidebar />
      <div className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8 pb-20 md:pb-8">
        <div className="max-w-2xl mx-auto">
          <div className="text-center mb-8">
            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-white">
              {'\u{1F4E4}'} Share & Export
            </h1>
            <p className="text-neutral-500 mt-1 text-sm">Share your progress or export your data</p>
          </div>

          {/* Report card preview */}
          <div ref={cardRef} className="bg-gradient-to-br from-neutral-900 via-neutral-900 to-indigo-950 border border-neutral-700 rounded-2xl p-6 mb-6">
            <div className="flex items-center gap-4 mb-5">
              <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-2xl font-bold text-white">
                E
              </div>
              <div>
                <h2 className="text-lg font-bold text-white m-0">{data.name}</h2>
                <p className="text-sm text-indigo-400 m-0">Level {data.level} {'\u00B7'} {data.title}</p>
              </div>
              <div className="ml-auto text-right">
                <p className="text-amber-400 font-bold text-lg m-0">{data.xp.toLocaleString()} XP</p>
              </div>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-5">
              <div className="bg-neutral-800/50 rounded-xl p-3 text-center">
                <p className="text-lg font-bold text-white m-0">{data.streak}</p>
                <p className="text-[10px] text-neutral-500 m-0">{'\u{1F525}'} Streak</p>
              </div>
              <div className="bg-neutral-800/50 rounded-xl p-3 text-center">
                <p className="text-lg font-bold text-white m-0">{data.quizCount}</p>
                <p className="text-[10px] text-neutral-500 m-0">{'\u{1F4DD}'} Quizzes</p>
              </div>
              <div className="bg-neutral-800/50 rounded-xl p-3 text-center">
                <p className="text-lg font-bold text-white m-0">{data.accuracy}%</p>
                <p className="text-[10px] text-neutral-500 m-0">{'\u{1F3AF}'} Accuracy</p>
              </div>
              <div className="bg-neutral-800/50 rounded-xl p-3 text-center">
                <p className="text-lg font-bold text-white m-0">{data.achievements}</p>
                <p className="text-[10px] text-neutral-500 m-0">{'\u{1F3C6}'} Badges</p>
              </div>
            </div>

            <div className="flex flex-wrap gap-1.5">
              {data.subjects.map(s => (
                <span key={s.subject} className="bg-indigo-500/15 text-indigo-400 text-[10px] font-semibold px-2 py-0.5 rounded-md">
                  {s.subject}
                </span>
              ))}
            </div>

            <p className="text-neutral-700 text-[9px] mt-4 m-0 text-right">Educate GCSE Revision App</p>
          </div>

          {/* Action buttons */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <button
              onClick={copyTextReport}
              className="bg-neutral-900 border border-neutral-800 rounded-2xl p-4 flex items-center gap-3 cursor-pointer hover:border-indigo-500/40 transition-all text-left"
            >
              <span className="text-2xl">{'\u{1F4CB}'}</span>
              <div>
                <p className="text-sm font-bold text-white m-0">Copy Report</p>
                <p className="text-xs text-neutral-500 m-0">Copy progress summary to clipboard</p>
              </div>
            </button>

            <button
              onClick={downloadTextReport}
              className="bg-neutral-900 border border-neutral-800 rounded-2xl p-4 flex items-center gap-3 cursor-pointer hover:border-indigo-500/40 transition-all text-left"
            >
              <span className="text-2xl">{'\u{1F4E5}'}</span>
              <div>
                <p className="text-sm font-bold text-white m-0">Download Report</p>
                <p className="text-xs text-neutral-500 m-0">Save as text file</p>
              </div>
            </button>

            <button
              onClick={downloadTimetablePrint}
              className="bg-neutral-900 border border-neutral-800 rounded-2xl p-4 flex items-center gap-3 cursor-pointer hover:border-indigo-500/40 transition-all text-left"
            >
              <span className="text-2xl">{'\u{1F5A8}\uFE0F'}</span>
              <div>
                <p className="text-sm font-bold text-white m-0">Export Timetable</p>
                <p className="text-xs text-neutral-500 m-0">Printable HTML timetable</p>
              </div>
            </button>

            <button
              onClick={() => {
                const url = window.location.origin;
                navigator.clipboard.writeText(`Check out Educate for GCSE revision! ${url}`);
                showToast({ icon: '\u{1F517}', title: 'Link copied!', type: 'success' });
              }}
              className="bg-neutral-900 border border-neutral-800 rounded-2xl p-4 flex items-center gap-3 cursor-pointer hover:border-indigo-500/40 transition-all text-left"
            >
              <span className="text-2xl">{'\u{1F517}'}</span>
              <div>
                <p className="text-sm font-bold text-white m-0">Share Educate</p>
                <p className="text-xs text-neutral-500 m-0">Copy link to share with friends</p>
              </div>
            </button>
          </div>
        </div>
      </div>
      <MobileNav />
    </div>
  );
}
